[package]
name = "deskmirror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dxgcap = "0.2.4"
iced = {version = "0.4.2", features = ["image"]}